# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hamr_interface/MotorStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorStatus(genpy.Message):
  _md5sum = "15945dc3aa5ce3ad70aaaff6085229e9"
  _type = "hamr_interface/MotorStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 position
int16 velocity
int16 desired_velocity
int16 speed_cmd
int16 pidError"""
  __slots__ = ['position','velocity','desired_velocity','speed_cmd','pidError']
  _slot_types = ['uint16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,velocity,desired_velocity,speed_cmd,pidError

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = 0
      if self.velocity is None:
        self.velocity = 0
      if self.desired_velocity is None:
        self.desired_velocity = 0
      if self.speed_cmd is None:
        self.speed_cmd = 0
      if self.pidError is None:
        self.pidError = 0
    else:
      self.position = 0
      self.velocity = 0
      self.desired_velocity = 0
      self.speed_cmd = 0
      self.pidError = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_H4h.pack(_x.position, _x.velocity, _x.desired_velocity, _x.speed_cmd, _x.pidError))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.position, _x.velocity, _x.desired_velocity, _x.speed_cmd, _x.pidError,) = _struct_H4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_H4h.pack(_x.position, _x.velocity, _x.desired_velocity, _x.speed_cmd, _x.pidError))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.position, _x.velocity, _x.desired_velocity, _x.speed_cmd, _x.pidError,) = _struct_H4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_H4h = struct.Struct("<H4h")
