(cl:in-package hamr_test-msg)
(cl:export '(SENSED_T_MOTOR_ENC_VALUE-VAL
          SENSED_T_MOTOR_ENC_VALUE
          SENSED_T_MOTOR_VELOCITY-VAL
          SENSED_T_MOTOR_VELOCITY
          SENSED_TURRET_POSITION-VAL
          SENSED_TURRET_POSITION
          SENSED_TURRET_VELOCITY-VAL
          SENSED_TURRET_VELOCITY
          DESIRED_TURRET_VELOCITY-VAL
          DESIRED_TURRET_VELOCITY
          PID_ERROR-VAL
          PID_ERROR
))