// Generated by gencpp from file hamr_interface/HamrCommand.msg
// DO NOT EDIT!


#ifndef HAMR_INTERFACE_MESSAGE_HAMRCOMMAND_H
#define HAMR_INTERFACE_MESSAGE_HAMRCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hamr_interface
{
template <class ContainerAllocator>
struct HamrCommand_
{
  typedef HamrCommand_<ContainerAllocator> Type;

  HamrCommand_()
    : type(0)
    , val()  {
    }
  HamrCommand_(const ContainerAllocator& _alloc)
    : type(0)
    , val(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _val_type;
  _val_type val;




  typedef boost::shared_ptr< ::hamr_interface::HamrCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hamr_interface::HamrCommand_<ContainerAllocator> const> ConstPtr;

}; // struct HamrCommand_

typedef ::hamr_interface::HamrCommand_<std::allocator<void> > HamrCommand;

typedef boost::shared_ptr< ::hamr_interface::HamrCommand > HamrCommandPtr;
typedef boost::shared_ptr< ::hamr_interface::HamrCommand const> HamrCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hamr_interface::HamrCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hamr_interface::HamrCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hamr_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hamr_interface': ['/home/modlab/Documents/hamr-ros/src/hamr_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hamr_interface::HamrCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hamr_interface::HamrCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hamr_interface::HamrCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hamr_interface::HamrCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hamr_interface::HamrCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hamr_interface::HamrCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hamr_interface::HamrCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0eca423a614570219cbd98b94133660e";
  }

  static const char* value(const ::hamr_interface::HamrCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0eca423a61457021ULL;
  static const uint64_t static_value2 = 0x9cbd98b94133660eULL;
};

template<class ContainerAllocator>
struct DataType< ::hamr_interface::HamrCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hamr_interface/HamrCommand";
  }

  static const char* value(const ::hamr_interface::HamrCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hamr_interface::HamrCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 type\n\
string val\n\
";
  }

  static const char* value(const ::hamr_interface::HamrCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hamr_interface::HamrCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HamrCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hamr_interface::HamrCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hamr_interface::HamrCommand_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "val: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAMR_INTERFACE_MESSAGE_HAMRCOMMAND_H
