// Generated by gencpp from file hamr_test/TestMod.msg
// DO NOT EDIT!


#ifndef HAMR_TEST_MESSAGE_TESTMOD_H
#define HAMR_TEST_MESSAGE_TESTMOD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hamr_test
{
template <class ContainerAllocator>
struct TestMod_
{
  typedef TestMod_<ContainerAllocator> Type;

  TestMod_()
    : num_one(0)
    , num_two(0)  {
    }
  TestMod_(const ContainerAllocator& _alloc)
    : num_one(0)
    , num_two(0)  {
  (void)_alloc;
    }



   typedef int8_t _num_one_type;
  _num_one_type num_one;

   typedef int8_t _num_two_type;
  _num_two_type num_two;




  typedef boost::shared_ptr< ::hamr_test::TestMod_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hamr_test::TestMod_<ContainerAllocator> const> ConstPtr;

}; // struct TestMod_

typedef ::hamr_test::TestMod_<std::allocator<void> > TestMod;

typedef boost::shared_ptr< ::hamr_test::TestMod > TestModPtr;
typedef boost::shared_ptr< ::hamr_test::TestMod const> TestModConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hamr_test::TestMod_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hamr_test::TestMod_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hamr_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hamr_test': ['/home/modlab/Documents/hamr-ros/src/hamr_test/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hamr_test::TestMod_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hamr_test::TestMod_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hamr_test::TestMod_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hamr_test::TestMod_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hamr_test::TestMod_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hamr_test::TestMod_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hamr_test::TestMod_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0958ec2ab25bba936759a90958b68a4c";
  }

  static const char* value(const ::hamr_test::TestMod_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0958ec2ab25bba93ULL;
  static const uint64_t static_value2 = 0x6759a90958b68a4cULL;
};

template<class ContainerAllocator>
struct DataType< ::hamr_test::TestMod_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hamr_test/TestMod";
  }

  static const char* value(const ::hamr_test::TestMod_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hamr_test::TestMod_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 num_one\n\
int8 num_two\n\
";
  }

  static const char* value(const ::hamr_test::TestMod_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hamr_test::TestMod_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_one);
      stream.next(m.num_two);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TestMod_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hamr_test::TestMod_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hamr_test::TestMod_<ContainerAllocator>& v)
  {
    s << indent << "num_one: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num_one);
    s << indent << "num_two: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num_two);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAMR_TEST_MESSAGE_TESTMOD_H
